### ISSUE TITLE
CPU version

### ISSUE THREAD

**Issue by loretoparisi** [JusperLee/Conv-TasNet#20]
Is it possibile to adapt the code run over CPU?

Currently if I try I get

```bash
# python Separation_wav.py -mix_scp /root/audio/test.wav -yaml options/train/train.yml -model /root/convtasnet/best.pt -save_path ./checkpoint
2020-12-21 11:44:09 [/app/option.py:13 - INFO ] Reading .yml file .......
2020-12-21 11:44:09 [/app/option.py:19 - INFO ] Export CUDA_VISIBLE_DEVICES = 1,2,3,4,5,6,7
2020-12-21 11:44:09 [Separation_wav.py:23 - INFO ] Load checkpoint from /root/convtasnet/best.pt, epoch  70
Traceback (most recent call last):
  File "Separation_wav.py", line 70, in <module>
    main()
  File "Separation_wav.py", line 65, in main
    separation=Separation(args.mix_scp, args.yaml, args.model, gpuid)
  File "Separation_wav.py", line 24, in __init__
    self.net=net.cuda()
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 305, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 202, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 224, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 305, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 192, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 102, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```

Thank you

**Comment by loretoparisi** [comment]
**[UPDATE]**
I was able to run in cpu slightly modifying the file `options/options.py`:

```python
# Export CUDA_VISIBLE_DEVICES
    if 'gpu_ids' in opt:
        gpu_list = ','.join(str(x) for x in opt['gpu_ids'])
        os.environ['CUDA_VISIBLE_DEVICES'] = gpu_list
        logger.info('Export CUDA_VISIBLE_DEVICES = {}'.format(gpu_list))
    else:
        os.environ['CUDA_VISIBLE_DEVICES'] = "-1"
```

and the method `Separation#__init__` file `Separation_wav.py` at 

```python
class Separation():
    def __init__(self, mix_path, yaml_path, model, gpuid=None):
        super(Separation, self).__init__()
        self.mix = read_wav(mix_path)
        opt = parse(yaml_path, is_tain=False)
        net = ConvTasNet(**opt['net_conf'])
        dicts = torch.load(model, map_location='cpu')
        net.load_state_dict(dicts["model_state_dict"])
        self.logger = get_logger(__name__)
        self.logger.info('Load checkpoint from {}, epoch {: d}'.format(model, dicts["epoch"]))
        
        if gpuid:
            self.logger.info("init gpu at", gpuid)
            self.net=net.cuda()
            self.device=torch.device('cuda:{}'.format(
                gpuid[0]) if len(gpuid) > 0 else 'cpu')
            self.gpuid=tuple(gpuid)
        else:
            self.gpuid = []
            self.net=net
            self.device = torch.device("cpu")
```

The problem is that the result is weird. For a given tiny test `wav` file of length `2 sec`

```
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from '/Users/loretoparisi/audio/test.wav':
  Metadata:
    encoder         : Lavf58.45.100
  Duration: 00:00:02.00, bitrate: 1411 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s
 ```

I get two files of size `11 sec`:

```bash
2020-12-21 13:11:38 [./options/option.py:13 - INFO ] Reading .yml file .......
2020-12-21 13:11:38 [Separation_wav.py:23 - INFO ] Load checkpoint from /root/convtasnet/best.pt, epoch  70
2020-12-21 13:12:23 [Separation_wav.py:59 - INFO ] Compute over 2 utterances
```

where output files are

```bash
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from '/Users/loretoparisi/tests/1.wav':
  Duration: 00:00:11.02, bitrate: 256 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 8000 Hz, stereo, s16, 256 kb/s
```

and

```
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from '/Users/loretoparisi/tests/2.wav':
  Duration: 00:00:11.02, bitrate: 256 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 8000 Hz, stereo, s16, 256 kb/s
```

**Comment by JusperLee** [comment]
You need to change the parameter of sample rate to adapt to the sample rate of your audio file. I set it to 8khz myself.

**Comment by loretoparisi** [comment]
> You need to change the parameter of sample rate to adapt to the sample rate of your audio file. I set it to 8khz myself.

Thank you it worked converting at 8000 Hz.
