### ISSUE TITLE
训练时出错

### ISSUE THREAD

**Issue by layers33** [JusperLee/Conv-TasNet#47]
您好，我在使用Conv_TasNet_Pytorch中的train.py进行训练时遇到了如下报错：
```
/home/layers/miniconda3/envs/asteroid/lib/python3.7/site-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  '"sox" backend is being deprecated. '
2023-04-14 17:28:59 [./options/option.py:13 - INFO ] Reading .yml file .......
2023-04-14 17:28:59 [./options/option.py:19 - INFO ] Export CUDA_VISIBLE_DEVICES = 0
2023-04-14 17:28:59 [train.py:20 - INFO ] Building the model of Conv-TasNet
2023-04-14 17:28:59 [train.py:23 - INFO ] Building the trainer of Conv-TasNet
2023-04-14 17:29:00 [/home/layers/audio/speech_enhancement/Conv-TasNet/Conv_TasNet_Pytorch/trainer.py:136 - INFO ] Create optimizer adam: {'lr': 0.001, 'weight_decay': 1e-05}
2023-04-14 17:29:00 [/home/layers/audio/speech_enhancement/Conv-TasNet/Conv_TasNet_Pytorch/trainer.py:105 - INFO ] Starting preparing model ............
2023-04-14 17:29:00 [/home/layers/audio/speech_enhancement/Conv-TasNet/Conv_TasNet_Pytorch/trainer.py:107 - INFO ] Loading model to GPUs:(0,), #param: 3.48M
2023-04-14 17:29:00 [/home/layers/audio/speech_enhancement/Conv-TasNet/Conv_TasNet_Pytorch/trainer.py:112 - INFO ] Gradient clipping by 200, default L2
2023-04-14 17:29:00 [train.py:28 - INFO ] Making the train and test data loader
Traceback (most recent call last):
  File "train.py", line 38, in <module>
    main()
  File "train.py", line 33, in main
    logger.info('Train data loader: {}, Test data loader: {}'.format(len(train_loader), len(val_loader)))
TypeError: object of type 'DataLoaders' has no len()
```
请问这是什么原因造成的呢？另外，我发现有dataloader.py和dataloader_new.py两个文件，而目前的train.py中使用的是dataloader.py，我是否应该使用dataloader_new.py？

**Comment by JusperLee** [comment]
https://github.com/JusperLee/Conv-TasNet/blob/1a6cfb90aab0fb4c2728f0e36750076b80ee4891/Conv_TasNet_Pytorch/DataLoaders.py#L98

你可以在这个位置添加以下代码
```python
def __len__(self, ):
    return len(self.data_loader)
```
